# print("my name is avnit")
a = str(1) 
print("this is value of a",str(a), str(type(a)))
b = 1.1 
print(type(b))
c = complex(a,b)
print(type(c))
print(c)
print("The real part of complex number is: ",c.real)
print("The imaginary part of complex number is: ",c.imag)
d = 1+2j
print(type(d))
print(d)
print("The real part of complex number is: ",d.real)
print("The imaginary part of complex number is: ",d.imag)